-- ============================================
-- Supabase Authentication Configuration
-- ============================================
-- JWT Configuration and Auth Policies
-- Created: 2025-01-31

-- ============================================
-- 1. ENABLE AUTHENTICATION
-- ============================================

-- Supabase Auth is enabled by default
-- JWT_SECRET is auto-generated by Supabase
-- Modify in Supabase Dashboard → Authentication → Providers

-- ============================================
-- 2. EMAIL PROVIDER CONFIGURATION
-- ============================================

-- Email provider is pre-configured in Supabase
-- Default: Email with confirmation link
-- Can be customized in Dashboard

-- Configuration parameters:
-- - AUTOCONFIRM: false (requires email verification)
-- - OTP_LENGTH: 6 digits
-- - OTP_EXPIRY: 3600 seconds (1 hour)

-- ============================================
-- 3. PASSWORD POLICY
-- ============================================

-- Recommended minimum requirements:
-- - Minimum length: 12 characters
-- - Complexity: Mix of uppercase, lowercase, numbers, symbols
-- - History: Don't reuse last 5 passwords

-- Supabase defaults (configurable):
-- - Min length: 6 characters (UPDATE THIS)
-- - No complexity requirement by default

-- ============================================
-- 4. JWT CONFIGURATION
-- ============================================

-- JWT Token Structure:
-- Header: { "alg": "HS256", "typ": "JWT" }
-- Payload: { "sub": "user-id", "iss": "issuer", "exp": timestamp, ... }
-- Signature: HMAC-SHA256(header + payload, secret)

-- Token types:
-- - access_token: Short-lived (1 hour default)
-- - refresh_token: Long-lived (30 days default)

-- ============================================
-- 5. AUTH HOOKS & TRIGGERS
-- ============================================

-- Trigger: On user signup
-- Action: Create user profile entry
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER SET search_path = public
AS $$
BEGIN
  INSERT INTO public.users (id, email, created_at, updated_at)
  VALUES (new.id, new.email, now(), now())
  ON CONFLICT (id) DO NOTHING;
  RETURN new;
END;
$$;

-- Trigger execution
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- ============================================
-- 6. SESSION MANAGEMENT
-- ============================================

-- Session tracking (optional):
-- Track user sessions for security audit

CREATE TABLE IF NOT EXISTS user_sessions (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  jwt_token TEXT NOT NULL,
  user_agent TEXT,
  ip_address INET,
  is_active BOOLEAN DEFAULT true,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  expires_at TIMESTAMP WITH TIME ZONE,
  revoked_at TIMESTAMP WITH TIME ZONE
);

CREATE INDEX idx_user_sessions_user_id ON user_sessions(user_id);
CREATE INDEX idx_user_sessions_active ON user_sessions(is_active);

-- ============================================
-- 7. PASSWORD RESET CONFIGURATION
-- ============================================

-- Password reset flow:
-- 1. User requests password reset
-- 2. Supabase sends reset link via email
-- 3. Link valid for 1 hour (configurable)
-- 4. User sets new password
-- 5. All existing sessions invalidated

-- Reset token table (for audit):
CREATE TABLE IF NOT EXISTS password_resets (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  reset_token TEXT UNIQUE NOT NULL,
  is_used BOOLEAN DEFAULT false,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  expires_at TIMESTAMP WITH TIME ZONE,
  used_at TIMESTAMP WITH TIME ZONE
);

CREATE INDEX idx_password_resets_user_id ON password_resets(user_id);
CREATE INDEX idx_password_resets_token ON password_resets(reset_token);

-- ============================================
-- 8. AUDIT LOGGING FOR AUTH
-- ============================================

-- Log auth events (logins, logouts, password changes)
CREATE TABLE IF NOT EXISTS auth_events (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  user_id UUID REFERENCES users(id) ON DELETE SET NULL,
  event_type VARCHAR(50) NOT NULL, -- login, logout, password_change, etc
  status VARCHAR(50) NOT NULL, -- success, failed, etc
  ip_address INET,
  user_agent TEXT,
  error_message TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_auth_events_user_id ON auth_events(user_id);
CREATE INDEX idx_auth_events_type ON auth_events(event_type);
CREATE INDEX idx_auth_events_created_at ON auth_events(created_at DESC);

-- ============================================
-- 9. RATE LIMITING SETUP (Optional)
-- ============================================

-- For rate limiting, implement in application layer:
-- - Login attempts: Max 5 per 15 minutes
-- - Password reset: Max 3 per hour
-- - Registration: Max 10 per hour per IP

-- Tracking table:
CREATE TABLE IF NOT EXISTS rate_limit_logs (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  ip_address INET NOT NULL,
  endpoint VARCHAR(100) NOT NULL,
  attempt_count INTEGER DEFAULT 1,
  first_attempt TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  last_attempt TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  is_blocked BOOLEAN DEFAULT false
);

CREATE INDEX idx_rate_limit_ip ON rate_limit_logs(ip_address);
CREATE INDEX idx_rate_limit_endpoint ON rate_limit_logs(endpoint);

-- ============================================
-- 10. MULTI-FACTOR AUTHENTICATION (MFA) - OPTIONAL
-- ============================================

-- Future support for MFA:
-- - TOTP (Time-based One-Time Password)
-- - SMS OTP
-- - Backup codes

-- MFA table:
CREATE TABLE IF NOT EXISTS user_mfa (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  mfa_type VARCHAR(50) NOT NULL, -- totp, sms, backup_codes
  secret TEXT,
  is_enabled BOOLEAN DEFAULT false,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  verified_at TIMESTAMP WITH TIME ZONE
);

CREATE INDEX idx_user_mfa_user_id ON user_mfa(user_id);

-- ============================================
-- CONFIGURATION SUMMARY
-- ============================================

-- Email Provider: Enabled (configurable in Supabase Dashboard)
-- Password Policy: Min 6 chars (RECOMMENDED: 12 chars)
-- JWT Expiry: 1 hour (access_token), 30 days (refresh_token)
-- Session Tracking: Enabled (user_sessions table)
-- Password Reset: Enabled (via email)
-- Rate Limiting: Application layer
-- MFA: Optional (tables created, implementation pending)
-- Audit Logging: Enabled (auth_events table)

-- ============================================
-- POST-DEPLOYMENT CHECKLIST
-- ============================================

-- 1. Verify Supabase Auth is enabled in project settings
-- 2. Configure email provider (SMTP or SendGrid)
-- 3. Update password policy (min 12 chars recommended)
-- 4. Test email verification flow
-- 5. Test password reset flow
-- 6. Configure CORS for frontend domain
-- 7. Setup JWT secret (auto-generated, verify in settings)
-- 8. Enable rate limiting in application
-- 9. Configure secure session storage
-- 10. Test auth flows end-to-end

-- ============================================
-- End of Auth Configuration
-- ============================================
